-- CREACION DE SCHEMA
CREATE SCHEMA CHALLENGE;

-- CREACION DE TABLAS EN EL SCHEMA CREADO
DROP TABLE CHALLENGE.DEPARTMENTS;
CREATE TABLE CHALLENGE.DEPARTMENTS(
ID INTEGER,
DEPARTMENT VARCHAR(200)
);

DROP TABLE CHALLENGE.JOBS;
CREATE TABLE CHALLENGE.JOBS(
    ID INTEGER,
    JOB VARCHAR(200)
);

DROP TABLE CHALLENGE.HIRED_EMPLOYEES;
CREATE TABLE CHALLENGE.HIRED_EMPLOYEES(
    ID INTEGER,
    NAME VARCHAR(200),
    DATETIME VARCHAR(200),
    DEPARTMENT_ID INTEGER,
    JOB_ID INTEGER
)